export default () => ({
  appEnv: process.env.APP_ENV || 'development',
  mongodbUrl:
    process.env.MONGODB_CONNECTION_STRING || 'mongodb://localhost/nest',
  jwtSecret: process.env.JWT_SECRET || 'AS12aswhqws',
  jwtTokenExpiresIn: process.env.JWT_TOKEN_EXPIRES_IN || '1d',
  jwtOtpTokenExpiresIn: process.env.JWT_OTP_TOKEN_EXPIRES_IN || '1h',
  twilioAuthKey: process.env.TWILIO_AUTH_KEY || '',
  twilioAuthSecret: process.env.TWILIO_AUTH_SECRET || '',
  twilioVerifyServiceId: process.env.TWILIO_VERIFY_SERVICE_ID || '',
  twilioCountryNumber: process.env.TWILIO_COUNTRY_NUMBER || '+1',
  twilioTestNumbers: process.env.TWILIO_TEST_NUMBERS || '1234567890,0987654321',
  twilioTestCode: process.env.TWILIO_TEST_CODE || '123456',
  paymentApiUrl: process.env.PAYMENT_API_URL || '',
  paymentPrivateKey: process.env.PAYMENT_PRIVATE_KEY || '',
  paymentPrivateKeyPasswd: process.env.PAYMENT_PRIVATE_KEY_PASSWD || '',
  paymentTokenExpiresIn: process.env.PAYMENT_TOKEN_EXPIRES_IN || '1h',
  auth0Issuer: process.env.AUTH0_ISSUER || '',
  auth0Audience: process.env.AUTH0_AUDIENCE || '',
  auth0SecretKey: process.env.AUTH0_SECRET_KEY || '',
  defaultDatetime:
    process.env.DEFAULT_DATETIME || '2023-01-02T{HH:MM}:00+00:00',
  smtpHost: process.env.SMTP_HOST || '',
  smtpPort: process.env.SMTP_PORT || '',
  smtpFromName: process.env.SMTP_FROM_NAME || '',
  smtpFromEmail: process.env.SMTP_FROM_EMAIL || '',
  smtpUsername: process.env.SMTP_USERNAME || '',
  smtpPassword: process.env.SMTP_PASSWORD || '',
  appRegisterUrl: process.env.APP_REGISTER_URL || 'http://localhost:3000',
  appRegisterNormalUrl:
    process.env.APP_REGISTER_NORMAL_URL || 'http://localhost:3000',
  appConfirmEmailUrl:
    process.env.APP_CONFIRM_EMAIL_URL || 'http://localhost:3000',
  appReservationUrl:
    process.env.APP_RESERVATION_URL || 'http://localhost?id=[[rId]]',
  registerTokenExpiresIn: process.env.REGISTER_TOKEN_EXPIRES_IN || '10m',
  defaultTimezone: process.env.DEFAULT_TIMEZONE || 'UTC',
  saleCommissionRate: process.env.SALE_COMMISION_RATE || 0.15,
  couponServiceAppId: process.env.COUPON_SERVICE_APP_ID || '',
  couponServiceAppCode: process.env.COUPON_SERVICE_APP_CODE || '',
  couponServiceApiUrl: process.env.COUPON_SERVICE_API_URL || '',
  couponServiceSecretKey: process.env.COUPON_SERVICE_SECRET_KEY || '',
  couponTokenExpiresIn: process.env.COUPON_TOKEN_EXPIRES_IN || '1h',
  couponTicketTag: process.env.COUPON_SERVICE_TICKET_TAG || '',
  couponTicketTagId: process.env.COUPON_SERVICE_TICKET_TAG_ID || 0,
  systemAdminServiceUrl: process.env.SA_SERVICE_URL || '',
  systemAdminClientId: process.env.SA_SERVICE_CLIENT_ID || '',
  systemAdminClientSecret: process.env.SA_SERVICE_CLIENT_SECRET || '',
});
